export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const NEW_POST = 'NEW_POST';
export const UPVOTE_POST = 'UPVOTE_POST';
export const DOWNVOTE_POST = 'DOWNVOTE_POST';
export const NEW_COMMENT = 'NEW_COMMENT';
export const FETCH_TAGS = 'FETCH_TAGS';
export const UPVOTE_COMMENT = 'UPVOTE_COMMENT';
export const FETCH_MORE_POSTS='FETCH_MORE_POSTS';