export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_MORE_POSTS = "FETCH_MORE_POSTS";
export const NEW_POST = "NEW_POST";
export const UPVOTE_POST = "UPVOTE_POST";
export const DOWNVOTE_POST = "DOWNVOTE_POST";

export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const NEW_COMMENT = "NEW_COMMENT";
export const UPVOTE_COMMENT = "UPVOTE_COMMENT";
export const REMOVE_VOTE_COMMENT = "REMOVE_VOTE_COMMENT";

export const FETCH_TAGS = "FETCH_TAGS";

export const AUTH_USER = "AUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_NEW_COMMENT = "USER_NEW_COMMENT"
export const USER_NEW_POST = "USER_NEW_POST"
export const USER_UPVOTE_POST = "USER_UPVOTE_POST";
export const USER_DOWNVOTE_POST = "USER_DOWNVOTE_POST";
export const USER_REMOVE_VOTE_POST = "USER_REMOVE_VOTE_POST";
export const USER_UPVOTE_COMMENT = "USER_UPVOTE_COMMENT";
export const USER_REMOVE_VOTE_COMMENT = "USER_REMOVE_VOTE_COMMENT";

export const SHOW_MODAL = "SHOW_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
