export const LANGUAGE_MAP = new Map([
  ["abap", "ABAP"],
  ["abc", "ABC"],
  ["actionscript", "ActionScript"],
  ["ada", "ADA"],
  ["apache_conf", "ApacheConf"],
  ["asciidoc", "AsciiDoc"],
  ["assembly_x86", "Assemblyx86"],
  ["autohotkey", "AutoHotkey/AutoIt"],
  ["batchfile", "BatchFile"],
  ["bro", "Bro"],
  ["c_cpp", "CandC++"],
  ["c9search", "C9Search"],
  ["cirru", "Cirru"],
  ["clojure", "Clojure"],
  ["cobol", "Cobol"],
  ["coffee", "CoffeeScript"],
  ["coldfusion", "ColdFusion"],
  ["csharp", "C#"],
  ["csound_document", "CsoundDocument"],
  ["csound_orchestra", "Csound"],
  ["csound_score", "CsoundScore"],
  ["css", "CSS"],
  ["curly", "Curly"],
  ["d", "D"],
  ["dart", "Dart"],
  ["diff", "Diff"],
  ["dockerfile", "Dockerfile"],
  ["dot", "Dot"],
  ["drools", "Drools"],
  ["eiffel", "Eiffel"],
  ["ejs", "EJS"],
  ["elixir", "Elixir"],
  ["elm", "Elm"],
  ["erlang", "Erlang"],
  ["forth", "Forth"],
  ["fortran", "Fortran"],
  ["ftl", "FreeMarker"],
  ["gcode", "Gcode"],
  ["gherkin", "Gherkin"],
  ["gitignore", "Gitignore"],
  ["glsl", "Glsl"],
  ["gobstones", "Gobstones"],
  ["golang", "Go"],
  ["graphqlschema", "GraphQLSchema"],
  ["groovy", "Groovy"],
  ["haml", "HAML"],
  ["handlebars", "Handlebars"],
  ["haskell", "Haskell"],
  ["haskell_cabal", "HaskellCabal"],
  ["haxe", "haXe"],
  ["hjson", "Hjson"],
  ["html", "HTML"],
  ["html_elixir", "HTML(Elixir)"],
  ["html_ruby", "HTML(Ruby)"],
  ["ini", "INI"],
  ["io", "Io"],
  ["jack", "Jack"],
  ["jade", "Jade"],
  ["java", "Java"],
  ["javascript", "JavaScript"],
  ["json", "JSON"],
  ["jsoniq", "JSONiq"],
  ["jsp", "JSP"],
  ["jssm", "JSSM"],
  ["jsx", "JSX"],
  ["julia", "Julia"],
  ["kotlin", "Kotlin"],
  ["latex", "LaTeX"],
  ["less", "LESS"],
  ["liquid", "Liquid"],
  ["lisp", "Lisp"],
  ["livescript", "LiveScript"],
  ["logiql", "LogiQL"],
  ["lsl", "LSL"],
  ["lua", "Lua"],
  ["luapage", "LuaPage"],
  ["lucene", "Lucene"],
  ["makefile", "Makefile"],
  ["markdown", "Markdown"],
  ["mask", "Mask"],
  ["matlab", "MATLAB"],
  ["maze", "Maze"],
  ["mel", "MEL"],
  ["mushcode", "MUSHCode"],
  ["mysql", "MySQL"],
  ["nix", "Nix"],
  ["nsis", "NSIS"],
  ["objectivec", "Objective-C"],
  ["ocaml", "OCaml"],
  ["pascal", "Pascal"],
  ["perl", "Perl"],
  ["pgsql", "pgSQL"],
  ["php", "PHP"],
  ["pig", "Pig"],
  ["powershell", "Powershell"],
  ["praat", "Praat"],
  ["prolog", "Prolog"],
  ["properties", "Properties"],
  ["protobuf", "Protobuf"],
  ["python", "Python"],
  ["r", "R"],
  ["razor", "Razor"],
  ["rdoc", "RDoc"],
  ["red", "Red"],
  ["rhtml", "RHTML"],
  ["rst", "RST"],
  ["ruby", "Ruby"],
  ["rust", "Rust"],
  ["sass", "SASS"],
  ["scad", "SCAD"],
  ["scala", "Scala"],
  ["scheme", "Scheme"],
  ["scss", "SCSS"],
  ["sh", "SH"],
  ["sjs", "SJS"],
  ["smarty", "Smarty"],
  ["snippets", "snippets"],
  ["soy_template", "SoyTemplate"],
  ["space", "Space"],
  ["sql", "SQL"],
  ["sqlserver", "SQLServer"],
  ["stylus", "Stylus"],
  ["svg", "SVG"],
  ["swift", "Swift"],
  ["tcl", "Tcl"],
  ["tex", "Tex"],
  ["text", "Text"],
  ["textile", "Textile"],
  ["toml", "Toml"],
  ["tsx", "TSX"],
  ["twig", "Twig"],
  ["typescript", "Typescript"],
  ["vala", "Vala"],
  ["vbscript", "VBScript"],
  ["velocity", "Velocity"],
  ["verilog", "Verilog"],
  ["vhdl", "VHDL"],
  ["wollok", "Wollok"],
  ["xml", "XML"],
  ["xquery", "XQuery"],
  ["yaml", "YAML"],
  ["django", "Django"]
]);

export function getLanguageTheme(language) {
  var LANGUAGE_COLORS = new Map([
    ["abap", ["DeepPink", "Lime"]],
    ["abc", ["Yellow", "Wheat"]],
    ["actionscript", ["GreenYellow", "DarkGrey"]],
    ["ada", ["YellowGreen", "Green"]],
    ["apache_conf", ["BlanchedAlmond", "Magenta"]],
    ["asciidoc", ["CornflowerBlue", "SaddleBrown"]],
    ["assembly_x86", ["Ivory", "SlateGray"]],
    ["autohotkey", ["Sienna", "Brown"]],
    ["batchfile", ["Violet", "LightSalmon"]],
    ["bro", ["Salmon", "Beige"]],
    ["c_cpp", ["darkblue", "LightSteelBlue"]],
    ["c9search", ["Khaki", "PaleGoldenRod"]],
    ["cirru", ["PapayaWhip", "AntiqueWhite"]],
    ["clojure", ["DarkOliveGreen", "Thistle"]],
    ["cobol", ["Gold", "MintCream"]],
    ["coffee", ["LightPink", "ForestGreen"]],
    ["coldfusion", ["PowderBlue", "GhostWhite"]],
    ["csharp", ["LightGray", "CornflowerBlue"]],
    ["csound_document", ["MediumTurquoise", "SeaShell"]],
    ["csound_orchestra", ["Turquoise", "LavenderBlush"]],
    ["csound_score", ["Lime", "Chocolate"]],
    ["css", ["MediumPurple", "SeaGreen"]],
    ["curly", ["MediumSeaGreen", "Yellow"]],
    ["d", ["DarkGreen", "BurlyWood"]],
    ["dart", ["DarkOrchid", "FloralWhite"]],
    ["diff", ["SlateGrey", "DarkOliveGreen"]],
    ["dockerfile", ["Tan", "Silver"]],
    ["dot", ["DarkViolet", "Navy"]],
    ["drools", ["DarkCyan", "OldLace"]],
    ["eiffel", ["DarkOrange", "BlueViolet"]],
    ["ejs", ["PeachPuff", "Orchid"]],
    ["elixir", ["LightSlateGray", "Cyan"]],
    ["elm", ["Linen", "DarkGray"]],
    ["erlang", ["lightpink", "SteelBlue"]],
    ["forth", ["LightCoral", "Gold"]],
    ["fortran", ["Azure", "Crimson"]],
    ["ftl", ["LawnGreen", "LawnGreen"]],
    ["gcode", ["PaleVioletRed", "DarkSeaGreen"]],
    ["gherkin", ["GhostWhite", "SlateBlue"]],
    ["gitignore", ["Brown", "DeepPink"]],
    ["glsl", ["Wheat", "MediumSlateBlue"]],
    ["gobstones", ["Orange", "DarkSalmon"]],
    ["golang", ["Teal", "LightSkyBlue"]],
    ["graphqlschema", ["Maroon", "DimGray"]],
    ["groovy", ["Gainsboro", "LemonChiffon"]],
    ["haml", ["Fuchsia", "Purple"]],
    ["handlebars", ["PaleTurquoise", "LightBlue"]],
    ["haskell", ["Coral", "MediumSpringGreen"]],
    ["haskell_cabal", ["DarkGoldenRod", "LightYellow"]],
    ["haxe", ["LightCyan", "MediumAquaMarine"]],
    ["hjson", ["Orchid", "MediumTurquoise"]],
    ["html", ["LightSteelBlue", "PapayaWhip"]],
    ["html_elixir", ["HoneyDew", "LightGray"]],
    ["html_ruby", ["DarkSlateGray", "NavajoWhite"]],
    ["ini", ["LightGreen", "SlateGrey"]],
    ["io", ["Lavender", "Lavender"]],
    ["jack", ["MediumSpringGreen", "Gray"]],
    ["jade", ["DarkRed", "MediumBlue"]],
    ["java", ["SteelBlue", "Violet"]],
    ["javascript", ["White", "DarkRed"]],
    ["json", ["BurlyWood", "MediumVioletRed"]],
    ["jsoniq", ["FireBrick", "SkyBlue"]],
    ["jsp", ["CadetBlue", "LimeGreen"]],
    ["jssm", ["RebeccaPurple", "Orange"]],
    ["jsx", ["LavenderBlush", "Sienna"]],
    ["julia", ["Green", "DarkViolet"]],
    ["kotlin", ["DarkMagenta", "Peru"]],
    ["latex", ["MediumSlateBlue", "Moccasin"]],
    ["less", ["FloralWhite", "Pink"]],
    ["liquid", ["DarkKhaki", "Aqua"]],
    ["lisp", ["DarkSeaGreen", "Ivory"]],
    ["livescript", ["Beige", "HoneyDew"]],
    ["logiql", ["Blue", "Gainsboro"]],
    ["lsl", ["Cornsilk", "PaleTurquoise"]],
    ["lua", ["DimGrey", "MediumSeaGreen"]],
    ["luapage", ["PaleGreen", "LightCoral"]],
    ["lucene", ["SeaGreen", "DarkGoldenRod"]],
    ["makefile", ["DodgerBlue", "PeachPuff"]],
    ["markdown", ["AntiqueWhite", "Maroon"]],
    ["mask", ["Navy", "HotPink"]],
    ["matlab", ["Aquamarine", "DarkMagenta"]],
    ["maze", ["Olive", "DimGrey"]],
    ["mel", ["RosyBrown", "DarkBlue"]],
    ["mushcode", ["LightSkyBlue", "OrangeRed"]],
    ["mysql", ["MintCream", "DeepSkyBlue"]],
    ["nix", ["Gray", "Turquoise"]],
    ["nsis", ["Cyan", "CadetBlue"]],
    ["objectivec", ["RoyalBlue", "DarkOrchid"]],
    ["ocaml", ["Magenta", "RoyalBlue"]],
    ["pascal", ["Chartreuse", "RebeccaPurple"]],
    ["perl", ["PaleGoldenRod", "Olive"]],
    ["pgsql", ["Grey", "Indigo "]],
    ["php", ["Crimson", "PaleVioletRed"]],
    ["pig", ["SaddleBrown", "Blue"]],
    ["powershell", ["SandyBrown", "MidnightBlue"]],
    ["praat", ["LemonChiffon", "Plum"]],
    ["prolog", ["OrangeRed", "Tan"]],
    ["properties", ["DarkSlateBlue", "DarkTurquoise"]],
    ["protobuf", ["HotPink", "OliveDrab"]],
    ["python", ["SlateGray", "LightGreen"]],
    ["r", ["MediumVioletRed", "Chartreuse"]],
    ["razor", ["DarkGrey", "Salmon"]],
    ["rdoc", ["MistyRose", "GreenYellow"]],
    ["red", ["DarkGray", "Aquamarine"]],
    ["rhtml", ["LightYellow", "SandyBrown"]],
    ["rst", ["Purple", "IndianRed "]],
    ["ruby", ["Bisque", "YellowGreen"]],
    ["rust", ["IndianRed ", "DarkSlateGrey"]],
    ["sass", ["LightSeaGreen", "Tomato"]],
    ["scad", ["NavajoWhite", "PowderBlue"]],
    ["scala", ["Moccasin", "Cornsilk"]],
    ["scheme", ["MediumAquaMarine", "Coral"]],
    ["scss", ["BlueViolet", "LightPink"]],
    ["sh", ["Red", "Black"]],
    ["sjs", ["Chocolate", "MediumOrchid"]],
    ["smarty", ["Snow", "LightSeaGreen"]],
    ["snippets", ["DarkSalmon", "RosyBrown"]],
    ["soy_template", ["OldLace", "DarkOrange"]],
    ["space", ["SeaShell", "DarkCyan"]],
    ["sql", ["WhiteSmoke", "Fuchsia"]],
    ["sqlserver", ["Black", "LightGrey"]],
    ["stylus", ["MediumOrchid", "LightSlateGray"]],
    ["svg", ["ForestGreen", "BlanchedAlmond"]],
    ["swift", ["MediumBlue", "Grey"]],
    ["tcl", ["SpringGreen", "DarkKhaki"]],
    ["tex", ["LightBlue", "PaleGreen"]],
    ["text", ["DarkTurquoise", "LightCyan"]],
    ["textile", ["SkyBlue", "LightGoldenRodYellow"]],
    ["toml", ["LimeGreen", "Bisque"]],
    ["tsx", ["Indigo ", "Azure"]],
    ["twig", ["GoldenRod", "DarkSlateBlue"]],
    ["typescript", ["Silver", "WhiteSmoke"]],
    ["vala", ["Tomato", "FireBrick"]],
    ["vbscript", ["LightGrey", "MistyRose"]],
    ["velocity", ["Plum", "DarkSlateGray"]],
    ["verilog", ["Pink", "Teal"]],
    ["vhdl", ["LightSalmon", "Khaki"]],
    ["wollok", ["MidnightBlue", "SpringGreen"]],
    ["xml", ["Peru", "Red"]],
    ["xquery", ["DeepSkyBlue", "Linen"]],
    ["yaml", ["Thistle", "DodgerBlue"]],
    ["django", ["LightSlateGrey", "MediumPurple"]]    
  ]);

  return {
    fg: LANGUAGE_COLORS.get(language)[0],
    bg: LANGUAGE_COLORS.get(language)[1]
  };
}
