export const LANGUAGE_LIST = [
    { value: "abap", label: "ABAP" },
    { value: "abc", label: "ABC" },
    { value: "actionscript", label: "ActionScript" },
    { value: "ada", label: "ADA" },
    { value: "apache_conf", label: "ApacheConf" },
    { value: "asciidoc", label: "AsciiDoc" },
    { value: "assembly_x86", label: "Assemblyx86" },
    { value: "autohotkey", label: "AutoHotkey/AutoIt" },
    { value: "batchfile", label: "BatchFile" },
    { value: "bro", label: "Bro" },
    { value: "c_cpp", label: "CandC++" },
    { value: "c9search", label: "C9Search" },
    { value: "cirru", label: "Cirru" },
    { value: "clojure", label: "Clojure" },
    { value: "cobol", label: "Cobol" },
    { value: "coffee", label: "CoffeeScript" },
    { value: "coldfusion", label: "ColdFusion" },
    { value: "csharp", label: "C#" },
    { value: "csound_document", label: "CsoundDocument" },
    { value: "csound_orchestra", label: "Csound" },
    { value: "csound_score", label: "CsoundScore" },
    { value: "css", label: "CSS" },
    { value: "curly", label: "Curly" },
    { value: "d", label: "D" },
    { value: "dart", label: "Dart" },
    { value: "diff", label: "Diff" },
    { value: "dockerfile", label: "Dockerfile" },
    { value: "dot", label: "Dot" },
    { value: "drools", label: "Drools" },
    { value: "eiffel", label: "Eiffel" },
    { value: "ejs", label: "EJS" },
    { value: "elixir", label: "Elixir" },
    { value: "elm", label: "Elm" },
    { value: "erlang", label: "Erlang" },
    { value: "forth", label: "Forth" },
    { value: "fortran", label: "Fortran" },
    { value: "ftl", label: "FreeMarker" },
    { value: "gcode", label: "Gcode" },
    { value: "gherkin", label: "Gherkin" },
    { value: "gitignore", label: "Gitignore" },
    { value: "glsl", label: "Glsl" },
    { value: "gobstones", label: "Gobstones" },
    { value: "golang", label: "Go" },
    { value: "graphqlschema", label: "GraphQLSchema" },
    { value: "groovy", label: "Groovy" },
    { value: "haml", label: "HAML" },
    { value: "handlebars", label: "Handlebars" },
    { value: "haskell", label: "Haskell" },
    { value: "haskell_cabal", label: "HaskellCabal" },
    { value: "haxe", label: "haXe" },
    { value: "hjson", label: "Hjson" },
    { value: "html", label: "HTML" },
    { value: "html_elixir", label: "HTML(Elixir)" },
    { value: "html_ruby", label: "HTML(Ruby)" },
    { value: "ini", label: "INI" },
    { value: "io", label: "Io" },
    { value: "jack", label: "Jack" },
    { value: "jade", label: "Jade" },
    { value: "java", label: "Java" },
    { value: "javascript", label: "JavaScript" },
    { value: "json", label: "JSON" },
    { value: "jsoniq", label: "JSONiq" },
    { value: "jsp", label: "JSP" },
    { value: "jssm", label: "JSSM" },
    { value: "jsx", label: "JSX" },
    { value: "julia", label: "Julia" },
    { value: "kotlin", label: "Kotlin" },
    { value: "latex", label: "LaTeX" },
    { value: "less", label: "LESS" },
    { value: "liquid", label: "Liquid" },
    { value: "lisp", label: "Lisp" },
    { value: "livescript", label: "LiveScript" },
    { value: "logiql", label: "LogiQL" },
    { value: "lsl", label: "LSL" },
    { value: "lua", label: "Lua" },
    { value: "luapage", label: "LuaPage" },
    { value: "lucene", label: "Lucene" },
    { value: "makefile", label: "Makefile" },
    { value: "markdown", label: "Markdown" },
    { value: "mask", label: "Mask" },
    { value: "matlab", label: "MATLAB" },
    { value: "maze", label: "Maze" },
    { value: "mel", label: "MEL" },
    { value: "mushcode", label: "MUSHCode" },
    { value: "mysql", label: "MySQL" },
    { value: "nix", label: "Nix" },
    { value: "nsis", label: "NSIS" },
    { value: "objectivec", label: "Objective-C" },
    { value: "ocaml", label: "OCaml" },
    { value: "pascal", label: "Pascal" },
    { value: "perl", label: "Perl" },
    { value: "pgsql", label: "pgSQL" },
    { value: "php", label: "PHP" },
    { value: "pig", label: "Pig" },
    { value: "powershell", label: "Powershell" },
    { value: "praat", label: "Praat" },
    { value: "prolog", label: "Prolog" },
    { value: "properties", label: "Properties" },
    { value: "protobuf", label: "Protobuf" },
    { value: "python", label: "Python" },
    { value: "r", label: "R" },
    { value: "razor", label: "Razor" },
    { value: "rdoc", label: "RDoc" },
    { value: "red", label: "Red" },
    { value: "rhtml", label: "RHTML" },
    { value: "rst", label: "RST" },
    { value: "ruby", label: "Ruby" },
    { value: "rust", label: "Rust" },
    { value: "sass", label: "SASS" },
    { value: "scad", label: "SCAD" },
    { value: "scala", label: "Scala" },
    { value: "scheme", label: "Scheme" },
    { value: "scss", label: "SCSS" },
    { value: "sh", label: "SH" },
    { value: "sjs", label: "SJS" },
    { value: "smarty", label: "Smarty" },
    { value: "snippets", label: "snippets" },
    { value: "soy_template", label: "SoyTemplate" },
    { value: "space", label: "Space" },
    { value: "sql", label: "SQL" },
    { value: "sqlserver", label: "SQLServer" },
    { value: "stylus", label: "Stylus" },
    { value: "svg", label: "SVG" },
    { value: "swift", label: "Swift" },
    { value: "tcl", label: "Tcl" },
    { value: "tex", label: "Tex" },
    { value: "text", label: "Text" },
    { value: "textile", label: "Textile" },
    { value: "toml", label: "Toml" },
    { value: "tsx", label: "TSX" },
    { value: "twig", label: "Twig" },
    { value: "typescript", label: "Typescript" },
    { value: "vala", label: "Vala" },
    { value: "vbscript", label: "VBScript" },
    { value: "velocity", label: "Velocity" },
    { value: "verilog", label: "Verilog" },
    { value: "vhdl", label: "VHDL" },
    { value: "wollok", label: "Wollok" },
    { value: "xml", label: "XML" },
    { value: "xquery", label: "XQuery" },
    { value: "yaml", label: "YAML" },
    { value: "django", label: "Django" },
];

export function getLanguageTheme(language) {

    var LANGUAGE_COLORS = new Map([
        ["abap", ["orangered", "lawngreen"]], 
        ["abc", ["green", "paleturquoise"]], 
        ["actionscript", ["orange", "cyan"]], 
        ["ada", ["indianred", "yellow"]], 
        ["apache_conf", ["moccasin", "palegoldenrod"]], 
        ["asciidoc", ["limegreen", "mediumseagreen"]], 
        ["assembly_x86", ["yellow", "olivedrab"]], 
        ["autohotkey", ["tomato", "seagreen"]], 
        ["batchfile", ["salmon", "lightcoral"]], 
        ["bro", ["lightsalmon", "springgreen"]], 
        ["c_cpp", ["darkorange", "lightgreen"]], 
        ["c9search", ["chartreuse", "limegreen"]], 
        ["cirru", ["indianred", "lime"]], 
        ["clojure", ["lightsalmon", "crimson"]], 
        ["cobol", ["salmon", "lightcyan"]], 
        ["coffee", ["papayawhip", "olivedrab"]], 
        ["coldfusion", ["lime", "darkseagreen"]], 
        ["csharp", ["orange", "olivedrab"]], 
        ["csound_document", ["darkseagreen", "darkolivegreen"]], 
        ["csound_orchestra", ["lightgoldenrodyellow", "greenyellow"]], 
        ["csound_score", ["red", "aquamarine"]], 
        ["css", ["lightcoral", "lightgreen"]], 
        ["curly", ["darkred", "darkgreen"]], 
        ["d", ["lightsalmon", "indianred"]], 
        ["dart", ["crimson", "green"]], 
        ["diff", ["palegoldenrod", "darkgreen"]], 
        ["dockerfile", ["lightyellow", "darkgreen"]], 
        ["dot", ["darkorange", "cyan"]], 
        ["drools", ["lightcoral", "mediumaquamarine"]], 
        ["eiffel", ["orangered", "darkkhaki"]], 
        ["ejs", ["red", "limegreen"]], 
        ["elixir", ["chartreuse", "lime"]], 
        ["elm", ["darkkhaki", "mediumseagreen"]], 
        ["erlang", ["lightsalmon", "palegoldenrod"]], 
        ["forth", ["darkred", "khaki"]], 
        ["fortran", ["lightsalmon", "olive"]], 
        ["ftl", ["gold", "olive"]], 
        ["gcode", ["darkseagreen", "darkolivegreen"]], 
        ["gherkin", ["darksalmon", "springgreen"]], 
        ["gitignore", ["forestgreen", "olive"]], 
        ["glsl", ["red", "palegreen"]], 
        ["gobstones", ["firebrick", "lightcyan"]], 
        ["golang", ["salmon", "lemonchiffon"]], 
        ["graphqlschema", ["darksalmon", "palegreen"]], 
        ["groovy", ["gold", "aqua"]], 
        ["haml", ["crimson", "mediumseagreen"]], 
        ["handlebars", ["lightgoldenrodyellow", "darkolivegreen"]], 
        ["haskell", ["lawngreen", "limegreen"]], 
        ["haskell_cabal", ["tomato", "lemonchiffon"]], 
        ["haxe", ["gold", "lime"]], 
        ["hjson", ["lightgoldenrodyellow", "yellowgreen"]], 
        ["html", ["tomato", "khaki"]], 
        ["html_elixir", ["orangered", "forestgreen"]], 
        ["html_ruby", ["lightsalmon", "chartreuse"]], 
        ["ini", ["darkred", "greenyellow"]], 
        ["io", ["darkolivegreen", "paleturquoise"]], 
        ["jack", ["mediumspringgreen", "cyan"]], 
        ["jade", ["coral", "yellowgreen"]], 
        ["java", ["orange", "darkolivegreen"]], 
        ["javascript", ["darkred", "aquamarine"]], 
        ["json", ["orangered", "cyan"]], 
        ["jsoniq", ["mediumseagreen", "olivedrab"]], 
        ["jsp", ["green", "yellowgreen"]], 
        ["jssm", ["darkorange", "mediumspringgreen"]], 
        ["jsx", ["mediumspringgreen", "aqua"]], 
        ["julia", ["darksalmon", "lawngreen"]], 
        ["kotlin", ["darkseagreen", "seagreen"]], 
        ["latex", ["coral", "yellow"]], 
        ["less", ["tomato", "lawngreen"]], 
        ["liquid", ["peachpuff", "mediumaquamarine"]], 
        ["lisp", ["lightcoral", "chartreuse"]], 
        ["livescript", ["coral", "lightyellow"]], 
        ["logiql", ["moccasin", "aqua"]], 
        ["lsl", ["darkorange", "mediumaquamarine"]], 
        ["lua", ["peachpuff", "green"]], 
        ["luapage", ["chartreuse", "limegreen"]], 
        ["lucene", ["darksalmon", "lightgoldenrodyellow"]], 
        ["makefile", ["orangered", "lightgreen"]], 
        ["markdown", ["khaki", "springgreen"]], 
        ["mask", ["khaki", "yellow"]], 
        ["matlab", ["mediumspringgreen", "aqua"]], 
        ["maze", ["darkred", "yellowgreen"]], 
        ["mel", ["lemonchiffon", "darkseagreen"]], 
        ["mushcode", ["peachpuff", "greenyellow"]], 
        ["mysql", ["lightcoral", "palegoldenrod"]], 
        ["nix", ["orangered", "forestgreen"]], 
        ["nsis", ["lightgreen", "olivedrab"]], 
        ["objectivec", ["red", "chartreuse"]], 
        ["ocaml", ["darkorange", "mediumaquamarine"]], 
        ["pascal", ["lightgoldenrodyellow", "greenyellow"]], 
        ["perl", ["forestgreen", "aquamarine"]], 
        ["pgsql", ["darkorange", "mediumspringgreen"]], 
        ["php", ["moccasin", "aqua"]], 
        ["pig", ["khaki", "olivedrab"]], 
        ["powershell", ["forestgreen", "olive"]], 
        ["praat", ["olive", "aquamarine"]], 
        ["prolog", ["red", "lightcyan"]], 
        ["properties", ["firebrick", "chartreuse"]], 
        ["protobuf", ["palegoldenrod", "lime"]], 
        ["python", ["darkgreen", "lightgreen"]], 
        ["r", ["khaki", "yellowgreen"]], 
        ["razor", ["salmon", "red"]], 
        ["rdoc", ["orangered", "mediumseagreen"]], 
        ["red", ["salmon", "paleturquoise"]], 
        ["rhtml", ["green", "yellowgreen"]], 
        ["rst", ["peachpuff", "paleturquoise"]], 
        ["ruby", ["forestgreen", "mediumspringgreen"]], 
        ["rust", ["indianred", "tomato"]], 
        ["sass", ["darkred", "darkkhaki"]], 
        ["scad", ["orange", "lightyellow"]], 
        ["scala", ["orange", "palegoldenrod"]], 
        ["scheme", ["yellow", "limegreen"]], 
        ["scss", ["salmon", "lemonchiffon"]], 
        ["sh", ["lightsalmon", "yellowgreen"]], 
        ["sjs", ["green", "darkseagreen"]], 
        ["smarty", ["lightyellow", "lightgoldenrodyellow"]], 
        ["snippets", ["lightgreen", "paleturquoise"]], 
        ["soy_template", ["lightsalmon", "indianred"]], 
        ["space", ["peachpuff", "greenyellow"]], 
        ["sql", ["darkkhaki", "palegreen"]], 
        ["sqlserver", ["darksalmon", "darkred"]], 
        ["stylus", ["lightgreen", "paleturquoise"]], 
        ["svg", ["red", "aqua"]], 
        ["swift", ["crimson", "palegoldenrod"]], 
        ["tcl", ["darkgreen", "cyan"]], 
        ["tex", ["salmon", "palegoldenrod"]], 
        ["text", ["crimson", "forestgreen"]], 
        ["textile", ["lightgoldenrodyellow", "olive"]], 
        ["toml", ["palegoldenrod", "mediumseagreen"]], 
        ["tsx", ["orange", "olivedrab"]], 
        ["twig", ["lemonchiffon", "darkolivegreen"]], 
        ["typescript", ["lawngreen", "darkseagreen"]], 
        ["vala", ["peachpuff", "paleturquoise"]], 
        ["vbscript", ["crimson", "red"]], 
        ["velocity", ["salmon", "lemonchiffon"]], 
        ["verilog", ["darksalmon", "lime"]], 
        ["vhdl", ["gold", "lightgreen"]], 
        ["wollok", ["darkred", "lemonchiffon"]], 
        ["xml", ["tomato", "darkgreen"]], 
        ["xquery", ["salmon", "palegoldenrod"]], 
        ["yaml", ["lightyellow", "greenyellow"]],
        ["django", ["darkred", "olive"]]
    ])

    return { fg: LANGUAGE_COLORS.get(language)[0], bg: LANGUAGE_COLORS.get(language)[1] };
}