export const LANGUAGE_MAP = new Map([
  ["abap", "ABAP"],
  ["abc", "ABC"],
  ["actionscript", "ActionScript"],
  ["ada", "ADA"],
  ["apache_conf", "ApacheConf"],
  ["asciidoc", "AsciiDoc"],
  ["assembly_x86", "Assemblyx86"],
  ["autohotkey", "AutoHotkey/AutoIt"],
  ["batchfile", "BatchFile"],
  ["bro", "Bro"],
  ["c_cpp", "CandC++"],
  ["c9search", "C9Search"],
  ["cirru", "Cirru"],
  ["clojure", "Clojure"],
  ["cobol", "Cobol"],
  ["coffee", "CoffeeScript"],
  ["coldfusion", "ColdFusion"],
  ["csharp", "C#"],
  ["csound_document", "CsoundDocument"],
  ["csound_orchestra", "Csound"],
  ["csound_score", "CsoundScore"],
  ["css", "CSS"],
  ["curly", "Curly"],
  ["d", "D"],
  ["dart", "Dart"],
  ["diff", "Diff"],
  ["dockerfile", "Dockerfile"],
  ["dot", "Dot"],
  ["drools", "Drools"],
  ["eiffel", "Eiffel"],
  ["ejs", "EJS"],
  ["elixir", "Elixir"],
  ["elm", "Elm"],
  ["erlang", "Erlang"],
  ["forth", "Forth"],
  ["fortran", "Fortran"],
  ["ftl", "FreeMarker"],
  ["gcode", "Gcode"],
  ["gherkin", "Gherkin"],
  ["gitignore", "Gitignore"],
  ["glsl", "Glsl"],
  ["gobstones", "Gobstones"],
  ["golang", "Go"],
  ["graphqlschema", "GraphQLSchema"],
  ["groovy", "Groovy"],
  ["haml", "HAML"],
  ["handlebars", "Handlebars"],
  ["haskell", "Haskell"],
  ["haskell_cabal", "HaskellCabal"],
  ["haxe", "haXe"],
  ["hjson", "Hjson"],
  ["html", "HTML"],
  ["html_elixir", "HTML(Elixir)"],
  ["html_ruby", "HTML(Ruby)"],
  ["ini", "INI"],
  ["io", "Io"],
  ["jack", "Jack"],
  ["jade", "Jade"],
  ["java", "Java"],
  ["javascript", "JavaScript"],
  ["json", "JSON"],
  ["jsoniq", "JSONiq"],
  ["jsp", "JSP"],
  ["jssm", "JSSM"],
  ["jsx", "JSX"],
  ["julia", "Julia"],
  ["kotlin", "Kotlin"],
  ["latex", "LaTeX"],
  ["less", "LESS"],
  ["liquid", "Liquid"],
  ["lisp", "Lisp"],
  ["livescript", "LiveScript"],
  ["logiql", "LogiQL"],
  ["lsl", "LSL"],
  ["lua", "Lua"],
  ["luapage", "LuaPage"],
  ["lucene", "Lucene"],
  ["makefile", "Makefile"],
  ["markdown", "Markdown"],
  ["mask", "Mask"],
  ["matlab", "MATLAB"],
  ["maze", "Maze"],
  ["mel", "MEL"],
  ["mushcode", "MUSHCode"],
  ["mysql", "MySQL"],
  ["nix", "Nix"],
  ["nsis", "NSIS"],
  ["objectivec", "Objective-C"],
  ["ocaml", "OCaml"],
  ["pascal", "Pascal"],
  ["perl", "Perl"],
  ["pgsql", "pgSQL"],
  ["php", "PHP"],
  ["pig", "Pig"],
  ["powershell", "Powershell"],
  ["praat", "Praat"],
  ["prolog", "Prolog"],
  ["properties", "Properties"],
  ["protobuf", "Protobuf"],
  ["python", "Python"],
  ["r", "R"],
  ["razor", "Razor"],
  ["rdoc", "RDoc"],
  ["red", "Red"],
  ["rhtml", "RHTML"],
  ["rst", "RST"],
  ["ruby", "Ruby"],
  ["rust", "Rust"],
  ["sass", "SASS"],
  ["scad", "SCAD"],
  ["scala", "Scala"],
  ["scheme", "Scheme"],
  ["scss", "SCSS"],
  ["sh", "SH"],
  ["sjs", "SJS"],
  ["smarty", "Smarty"],
  ["snippets", "snippets"],
  ["soy_template", "SoyTemplate"],
  ["space", "Space"],
  ["sql", "SQL"],
  ["sqlserver", "SQLServer"],
  ["stylus", "Stylus"],
  ["svg", "SVG"],
  ["swift", "Swift"],
  ["tcl", "Tcl"],
  ["tex", "Tex"],
  ["text", "Text"],
  ["textile", "Textile"],
  ["toml", "Toml"],
  ["tsx", "TSX"],
  ["twig", "Twig"],
  ["typescript", "Typescript"],
  ["vala", "Vala"],
  ["vbscript", "VBScript"],
  ["velocity", "Velocity"],
  ["verilog", "Verilog"],
  ["vhdl", "VHDL"],
  ["wollok", "Wollok"],
  ["xml", "XML"],
  ["xquery", "XQuery"],
  ["yaml", "YAML"],
  ["django", "Django"]
]);

export function getLanguageTheme(language) {
  var LANGUAGE_COLORS = new Map([
    ["abap", ["orangered", "lawngreen"]],
    ["abc", ["green", "paleturquoise"]],
    ["actionscript", ["orange", "cyan"]],
    ["ada", ["indianred", "yellow"]],
    ["apache_conf", ["limegreen", "palegoldenrod"]],
    ["asciidoc", ["limegreen", "mediumseagreen"]],
    ["assembly_x86", ["yellow", "olivedrab"]],
    ["autohotkey", ["tomato", "seagreen"]],
    ["batchfile", ["salmon", "lightcoral"]],
    ["bro", ["lightsalmon", "springgreen"]],
    ["c_cpp", ["red", "paleturquoise"]],
    ["c9search", ["chartreuse", "limegreen"]],
    ["cirru", ["indianred", "lime"]],
    ["clojure", ["lightsalmon", "crimson"]],
    ["cobol", ["salmon", "lightcyan"]],
    ["coffee", ["papayawhip", "olivedrab"]],
    ["coldfusion", ["lime", "darkseagreen"]],
    ["csharp", ["orange", "olivedrab"]],
    ["csound_document", ["darkseagreen", "darkolivegreen"]],
    ["csound_orchestra", ["lightgoldenrodyellow", "greenyellow"]],
    ["csound_score", ["red", "aquamarine"]],
    ["css", ["lightcoral", "lightgreen"]],
    ["curly", ["darkred", "darkgreen"]],
    ["d", ["lightsalmon", "indianred"]],
    ["dart", ["crimson", "green"]],
    ["diff", ["palegoldenrod", "darkgreen"]],
    ["dockerfile", ["lightyellow", "darkgreen"]],
    ["dot", ["darkorange", "cyan"]],
    ["drools", ["lightcoral", "mediumaquamarine"]],
    ["eiffel", ["orangered", "darkkhaki"]],
    ["ejs", ["red", "limegreen"]],
    ["elixir", ["chartreuse", "lime"]],
    ["elm", ["darkkhaki", "mediumseagreen"]],
    ["erlang", ["lightsalmon", "palegoldenrod"]],
    ["forth", ["darkred", "khaki"]],
    ["fortran", ["lightsalmon", "olive"]],
    ["ftl", ["gold", "olive"]],
    ["gcode", ["darkseagreen", "darkolivegreen"]],
    ["gherkin", ["darksalmon", "springgreen"]],
    ["gitignore", ["forestgreen", "olive"]],
    ["glsl", ["red", "palegreen"]],
    ["gobstones", ["firebrick", "lightcyan"]],
    ["golang", ["salmon", "lemonchiffon"]],
    ["graphqlschema", ["darksalmon", "palegreen"]],
    ["groovy", ["gold", "aqua"]],
    ["haml", ["crimson", "mediumseagreen"]],
    ["handlebars", ["lightgoldenrodyellow", "darkolivegreen"]],
    ["haskell", ["lawngreen", "darkred"]],
    ["haskell_cabal", ["tomato", "lemonchiffon"]],
    ["haxe", ["gold", "lime"]],
    ["hjson", ["lightgoldenrodyellow", "yellowgreen"]],
    ["html", ["tomato", "khaki"]],
    ["html_elixir", ["orangered", "forestgreen"]],
    ["html_ruby", ["lightsalmon", "chartreuse"]],
    ["ini", ["darkred", "greenyellow"]],
    ["io", ["darkolivegreen", "paleturquoise"]],
    ["jack", ["mediumspringgreen", "cyan"]],
    ["jade", ["coral", "yellowgreen"]],
    ["java", ["orange", "darkolivegreen"]],
    ["javascript", ["darkred", "aquamarine"]],
    ["json", ["orangered", "cyan"]],
    ["jsoniq", ["mediumseagreen", "olivedrab"]],
    ["jsp", ["green", "yellowgreen"]],
    ["jssm", ["darkorange", "mediumspringgreen"]],
    ["jsx", ["mediumspringgreen", "aqua"]],
    ["julia", ["darksalmon", "lawngreen"]],
    ["kotlin", ["darkseagreen", "seagreen"]],
    ["latex", ["coral", "yellow"]],
    ["less", ["tomato", "lawngreen"]],
    ["liquid", ["peachpuff", "mediumaquamarine"]],
    ["lisp", ["lightcoral", "chartreuse"]],
    ["livescript", ["coral", "lightyellow"]],
    ["logiql", ["moccasin", "aqua"]],
    ["lsl", ["darkorange", "mediumaquamarine"]],
    ["lua", ["peachpuff", "green"]],
    ["luapage", ["chartreuse", "limegreen"]],
    ["lucene", ["darksalmon", "lightgoldenrodyellow"]],
    ["makefile", ["orangered", "lightgreen"]],
    ["markdown", ["khaki", "springgreen"]],
    ["mask", ["khaki", "yellow"]],
    ["matlab", ["mediumspringgreen", "aqua"]],
    ["maze", ["darkred", "yellowgreen"]],
    ["mel", ["lemonchiffon", "darkseagreen"]],
    ["mushcode", ["peachpuff", "greenyellow"]],
    ["mysql", ["lightcoral", "palegoldenrod"]],
    ["nix", ["orangered", "forestgreen"]],
    ["nsis", ["lightgreen", "olivedrab"]],
    ["objectivec", ["red", "chartreuse"]],
    ["ocaml", ["peachpuff", "orangered"]],
    ["pascal", ["lightgoldenrodyellow", "greenyellow"]],
    ["perl", ["forestgreen", "aquamarine"]],
    ["pgsql", ["darkorange", "mediumspringgreen"]],
    ["php", ["moccasin", "aqua"]],
    ["pig", ["khaki", "olivedrab"]],
    ["powershell", ["forestgreen", "olive"]],
    ["praat", ["olive", "aquamarine"]],
    ["prolog", ["red", "lightcyan"]],
    ["properties", ["firebrick", "chartreuse"]],
    ["protobuf", ["palegoldenrod", "lime"]],
    ["python", ["darkgreen", "lightgreen"]],
    ["r", ["khaki", "yellowgreen"]],
    ["razor", ["salmon", "red"]],
    ["rdoc", ["orangered", "mediumseagreen"]],
    ["red", ["salmon", "paleturquoise"]],
    ["rhtml", ["green", "yellowgreen"]],
    ["rst", ["peachpuff", "paleturquoise"]],
    ["ruby", ["forestgreen", "mediumspringgreen"]],
    ["rust", ["khaki", "forestgreen"]],
    ["sass", ["darkred", "darkkhaki"]],
    ["scad", ["orange", "lightyellow"]],
    ["scala", ["orange", "palegoldenrod"]],
    ["scheme", ["yellow", "limegreen"]],
    ["scss", ["salmon", "lemonchiffon"]],
    ["sh", ["lightsalmon", "yellowgreen"]],
    ["sjs", ["green", "darkseagreen"]],
    ["smarty", ["lightyellow", "lightgoldenrodyellow"]],
    ["snippets", ["lightgreen", "paleturquoise"]],
    ["soy_template", ["lightsalmon", "indianred"]],
    ["space", ["peachpuff", "greenyellow"]],
    ["sql", ["darkkhaki", "palegreen"]],
    ["sqlserver", ["darksalmon", "darkred"]],
    ["stylus", ["lightgreen", "paleturquoise"]],
    ["svg", ["red", "aqua"]],
    ["swift", ["crimson", "palegoldenrod"]],
    ["tcl", ["darkgreen", "cyan"]],
    ["tex", ["salmon", "palegoldenrod"]],
    ["text", ["crimson", "forestgreen"]],
    ["textile", ["lightgoldenrodyellow", "olive"]],
    ["toml", ["palegoldenrod", "mediumseagreen"]],
    ["tsx", ["orange", "olivedrab"]],
    ["twig", ["lemonchiffon", "darkolivegreen"]],
    ["typescript", ["lawngreen", "darkseagreen"]],
    ["vala", ["peachpuff", "paleturquoise"]],
    ["vbscript", ["crimson", "red"]],
    ["velocity", ["salmon", "lemonchiffon"]],
    ["verilog", ["darksalmon", "lime"]],
    ["vhdl", ["gold", "lightgreen"]],
    ["wollok", ["darkred", "lemonchiffon"]],
    ["xml", ["tomato", "darkgreen"]],
    ["xquery", ["salmon", "palegoldenrod"]],
    ["yaml", ["lightyellow", "greenyellow"]],
    ["django", ["darkred", "olive"]]
  ]);

  return {
    fg: LANGUAGE_COLORS.get(language)[0],
    bg: LANGUAGE_COLORS.get(language)[1]
  };
}
